name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master

steps:
- script: ls '$(System.DefaultWorkingDirectory)'

- script: |
    bash testscript/test_running_process.sh
  displayName: Check Uptime status
